# -*- coding: utf-8 -*-
"""Cópia de WoMakersCode - Bootcamp Back- End Python & Django

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOdT0eTUgaostT271K25CJTAX_U2EVNc

DESAFIO 1

Crie um programa que solicita ao usuário que insira três notas (valores de 0 a 10) e, em seguida, calcule e exiba a média dessas notas.

Além disso, informe ao usuário se ele foi aprovado ou reprovado com base na média das notas, considerando a média mínima de aprovação como 6.
"""

nota1 = float(input("Digite a primeira nota (de 0 a 10): "))
nota2 = float(input("Digite a segunda nota (de 0 a 10): "))
nota3 = float (input("Digite a terceira nota (de 0 a 10): "))

media = (nota1 + nota2 + nota3)/3

if media >=6:
  print(f"Sua média é {media:.2f}. Parabéns, aluno aprovado!")
else:
  print(f"Sua média é {media:.2f}. Infelizmente o aluno reprovou.")

"""DESAFIO 2

Crie um programa que solicita ao usuário que insira um número inteiro e, em seguida, verifica se o número é par ou ímpar.

O programa deve exibir uma mensagem indicando se o número é par ou ímpar.
"""

numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
  print(f"O número {numero} é par.")
else:
  print(f"O número {numero} é ímpar.")

"""DESAFIO 3

Crie um programa que verifica se uma palavra fornecida pelo usuário é um palíndromo ou não.

(Um palíndromo é uma palavra que é lida da mesma forma tanto da esquerda para a direita quanto da direita para a esquerda.)
"""

from types import TracebackType
def verifica_palindromo(palavra):

  palavra = palavra.replace ("", "").lower()

  if palavra == palavra [::-1]:
    return True
  else:
    return False

palavra_usuario = input("Digite uma palavra: ")

if verifica_palindromo(palavra_usuario):
  print(f"Apalavra '{palavra_usuario}' é um palíndromo!")
else:
  print(f"A pavra '{palavra_usuario}' não é um palíndrmo.")

"""DESAFIO 4

Crie um programa que solicita ao usuário que insira um número inteiro positivo e, em seguida, calcula e exibe o fatorial desse número.

(O fatorial de um número é o produto de todos os números inteiros positivos de 1 até o próprio número.)
"""

numero = int(input("Digite um número inteiro positivo: "))

if numero < 0:
  print("O número deve ser positivo.")
else:
  resultado = 1
  for i in range(1, numero + 1):
    resultado *= i

    print(f"O fatorial de {numero} é {resultado}.")

"""DESAFIO 5

Crie um programa que permita ao usuário gerenciar suas tarefas diárias. O programa deve oferecer as seguintes funcionalidades:

*   Adicionar uma nova tarefa;
*   Visualizar todas as tarefas;
*   Marcar uma tarefa como concluída;
*   Remover uma tarefa;
*   Sair do programa.

(Você pode implementar essas funcionalidades usando listas para armazenar as tarefas e estruturas de controle como loops e condicionais para interagir com o usuário.)
"""

lista_de_tarefas = []

def adicionar_tarefa():
  tarefa = input("Digite a nova tarefa: ")
  lista_de_tarefas.append(tarefa)
  print(f"Tarefa '{tarefa}' adicionada com sucesso!")

def visualizar_tarefas():
  if lista_de_tarefas:
    print("Tarefas:")
    for i, tarefa in enumerate(lista_de_tarefas, start=1):
      print(f"{i}. {tarefa}")
  else:
      print("Nenhuma tarefa encontrada.")

def marcar_como_concluida():
  visualizar_tarefas()
  numero_tarefa = int(input("Digite o número da tarefa concluída: "))
  if 1 <= numero_tarefa <= len(lista_de_tarefas):
    tarefa = lista_de_tarefas [numero_tarefa - 1]
  else:
    print("Número inválido")

def remover_tarefa():
  visualizar_tarefas()
  numero_tarefa = int(input("Digite o número da tarefa a ser removida: "))
  if 1 <= numero_tarefa <= len(lista_de_tarefas):
    tarefa = lista_de_tarefas[numero_tarefa - 1]
    print(f"Tarefa '{tarefa}' removida com sucesso!")
    lista_de_tarefas.pop(numero_tarefa - 1)
  else:
    print("Número de tarefa inválido.")

while True:
  print("\nMenu:")
  print("1. Adicionar tarefa")
  print("2. Visualizar tarefas")
  print("3. Marcar como concluída")
  print("4. remover tarefa")
  print("5. Sair")
  opcao = input("Escolha uma opção entre 1 e 5: ")

  if opcao == "1":
    adicionar_tarefa()
  elif opcao == "2":
    visualizar_tarefas()
  elif opcao == "3":
    marcar_como_concluida()
  elif opcao == "4":
    remover_tarefa()
  elif opcao == "5":
    print("Encerrando o programa. Até logo!")
    break
  else:
    print("Opção inválida. Escolha novamente.")